# Generated by Django 3.2 on 2021-05-05 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='personna',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.DeleteModel(
            name='UserPersona',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Rights',
            field=models.ManyToManyField(blank=True, to='accounts.UserRights'),
        ),
    ]
