# Generated by Django 3.2.1 on 2021-06-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_medical_pics_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('discription', models.CharField(max_length=255)),
                ('dossierid', models.ForeignKey(db_column='chirurgicauxid', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.dossier')),
            ],
        ),
    ]
