# Generated by Django 3.2 on 2021-05-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210505_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrights',
            name='Details',
            field=models.CharField(default='rights details', max_length=200),
        ),
    ]
