# Generated by Django 3.2.1 on 2021-06-10 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medical_pics',
        ),
    ]
