# Generated by Django 3.2.1 on 2021-05-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userrights_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsUsergroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'accounts_usergroups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsUserprofile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_full_name_displayed', models.BooleanField()),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'accounts_userprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsUserprofileRights',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'accounts_userprofile_Rights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsUserrights',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('details', models.CharField(db_column='Details', max_length=200)),
            ],
            options={
                'db_table': 'accounts_userrights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Allergiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allerg_1', models.CharField(blank=True, max_length=255, null=True)),
                ('allerg_2', models.CharField(blank=True, max_length=255, null=True)),
                ('allerg_3', models.CharField(blank=True, max_length=255, null=True)),
                ('allerg_4', models.BooleanField(blank=True, null=True)),
                ('allerg_5', models.CharField(blank=True, max_length=255, null=True)),
                ('allerg_6', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'allergiques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CardioVasculaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_1', models.BooleanField(blank=True, null=True)),
                ('card_2', models.BooleanField(blank=True, null=True)),
                ('card_3', models.BooleanField(blank=True, null=True)),
                ('card_4', models.BooleanField(blank=True, null=True)),
                ('card_5', models.BooleanField(blank=True, null=True)),
                ('card_6', models.BooleanField(blank=True, null=True)),
                ('card_7', models.BooleanField(blank=True, null=True)),
                ('card_8', models.BooleanField(blank=True, null=True)),
                ('card_9', models.BooleanField(blank=True, null=True)),
                ('card_10', models.CharField(blank=True, max_length=255, null=True)),
                ('card_11', models.DateField(blank=True, null=True)),
                ('card_12', models.BooleanField(blank=True, null=True)),
                ('card_13', models.BooleanField(blank=True, null=True)),
                ('card_14', models.BooleanField(blank=True, null=True)),
                ('card_15', models.BooleanField(blank=True, null=True)),
                ('card_16', models.BooleanField(blank=True, null=True)),
                ('card_17', models.BooleanField(blank=True, null=True)),
                ('card_18', models.BooleanField(blank=True, null=True)),
                ('card_19', models.BooleanField(blank=True, null=True)),
                ('card_20', models.BooleanField(blank=True, null=True)),
                ('card_21', models.BooleanField(blank=True, null=True)),
                ('card_22', models.BooleanField(blank=True, null=True)),
                ('card_23', models.BooleanField(blank=True, null=True)),
                ('card_24', models.BooleanField(blank=True, null=True)),
                ('card_25', models.BooleanField(blank=True, null=True)),
                ('card_26', models.BooleanField(blank=True, null=True)),
                ('card_27', models.BooleanField(blank=True, null=True)),
                ('card_28', models.BooleanField(blank=True, null=True)),
                ('card_29', models.BooleanField(blank=True, null=True)),
                ('card_30', models.BooleanField(blank=True, null=True)),
                ('card_31', models.BooleanField(blank=True, null=True)),
                ('card_32', models.BooleanField(blank=True, null=True)),
                ('card_33', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cardio_vasculaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chirurgicaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('churg_0', models.BooleanField(blank=True, null=True)),
                ('churg_1', models.CharField(blank=True, max_length=255, null=True)),
                ('churg_2', models.CharField(blank=True, max_length=255, null=True)),
                ('churg_3', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chirurgicaux',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dent_1', models.BooleanField(blank=True, null=True)),
                ('dent_2', models.BooleanField(blank=True, null=True)),
                ('dent_3', models.BooleanField(blank=True, null=True)),
                ('dent_4', models.BooleanField(blank=True, null=True)),
                ('dent_5', models.BooleanField(blank=True, null=True)),
                ('dent_6', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dentaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Digestifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_1', models.BooleanField(blank=True, null=True)),
                ('digest_2', models.BooleanField(blank=True, null=True)),
                ('digest_3', models.BooleanField(blank=True, null=True)),
                ('digest_4', models.BooleanField(blank=True, null=True)),
                ('digest_5', models.BooleanField(blank=True, null=True)),
                ('digest_6', models.BooleanField(blank=True, null=True)),
                ('digest_7', models.BooleanField(blank=True, null=True)),
                ('digest_8', models.CharField(blank=True, max_length=255, null=True)),
                ('digest_9', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'digestifs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Divers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dive_1', models.BooleanField(blank=True, null=True)),
                ('dive_2', models.BooleanField(blank=True, null=True)),
                ('dive_3', models.BooleanField(blank=True, null=True)),
                ('dive_4', models.CharField(blank=True, max_length=255, null=True)),
                ('dive_5', models.CharField(blank=True, max_length=255, null=True)),
                ('dive_6', models.CharField(blank=True, max_length=255, null=True)),
                ('div_7', models.BooleanField(blank=True, null=True)),
                ('div_8', models.BooleanField(blank=True, null=True)),
                ('div_9', models.BooleanField(blank=True, null=True)),
                ('div_10', models.BooleanField(blank=True, null=True)),
                ('div_11', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'divers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dossier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enceinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.BooleanField(blank=True, null=True)),
                ('b', models.IntegerField(blank=True, null=True)),
                ('c', models.BooleanField(blank=True, null=True)),
                ('g', models.BooleanField(blank=True, null=True)),
                ('h', models.CharField(blank=True, max_length=255, null=True)),
                ('i', models.DateField(blank=True, null=True)),
                ('j', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enceinte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meds', models.CharField(blank=True, max_length=255, null=True)),
                ('dose', models.CharField(blank=True, max_length=255, null=True)),
                ('matin', models.IntegerField(blank=True, null=True)),
                ('midi', models.IntegerField(blank=True, null=True)),
                ('soir', models.IntegerField(blank=True, null=True)),
                ('nuit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encours',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Familiaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famil_1', models.CharField(blank=True, max_length=255, null=True)),
                ('famil_2', models.CharField(blank=True, max_length=255, null=True)),
                ('famil_3', models.CharField(blank=True, max_length=255, null=True)),
                ('famil_4', models.CharField(blank=True, max_length=255, null=True)),
                ('famil_5', models.BooleanField(blank=True, null=True)),
                ('famil_6', models.BooleanField(blank=True, null=True)),
                ('famil_7', models.BooleanField(blank=True, null=True)),
                ('famil_8', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'familiaux',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cigarette', models.IntegerField(blank=True, null=True)),
                ('chicha', models.IntegerField(blank=True, null=True)),
                ('tabagisme', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fumer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gyneco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gyne_1', models.BooleanField(blank=True, null=True)),
                ('gyne_2', models.DateField(blank=True, null=True)),
                ('gyne_3', models.CharField(blank=True, max_length=255, null=True)),
                ('gyne_4', models.BooleanField(blank=True, null=True)),
                ('gyne_5', models.BooleanField(blank=True, null=True)),
                ('gyne_6', models.IntegerField(blank=True, null=True)),
                ('gyne_7', models.IntegerField(blank=True, null=True)),
                ('gyne_8', models.IntegerField(blank=True, null=True)),
                ('gyne_9', models.BooleanField(blank=True, null=True)),
                ('gyne_10', models.BooleanField(blank=True, null=True)),
                ('gyne_11', models.CharField(blank=True, max_length=255, null=True)),
                ('gyne_12', models.BooleanField(blank=True, null=True)),
                ('gyne_13', models.BooleanField(blank=True, null=True)),
                ('gyne_14', models.BooleanField(blank=True, null=True)),
                ('gyne_15', models.BooleanField(blank=True, null=True)),
                ('gyne_16', models.BooleanField(blank=True, null=True)),
                ('gyne_17', models.BooleanField(blank=True, null=True)),
                ('gyne_18', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gyneco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_1', models.BooleanField(blank=True, null=True)),
                ('habit_2', models.BooleanField(blank=True, null=True)),
                ('habit_3', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'habitudes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hematologiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemato_1', models.BooleanField(blank=True, null=True)),
                ('hemato_2', models.CharField(blank=True, max_length=255, null=True)),
                ('hemato_3', models.BooleanField(blank=True, null=True)),
                ('hemato_4', models.BooleanField(blank=True, null=True)),
                ('hemato_5', models.CharField(blank=True, max_length=255, null=True)),
                ('hemato_6', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'hematologiques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hormonaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horm_1', models.BooleanField(blank=True, null=True)),
                ('horm_2', models.BooleanField(blank=True, null=True)),
                ('horm_3', models.BooleanField(blank=True, null=True)),
                ('horm_4', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hormonaux',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImgDent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('discription', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'img_dent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Neurologiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neuro_1', models.BooleanField(blank=True, null=True)),
                ('neuro_2', models.BooleanField(blank=True, null=True)),
                ('neuro_3', models.BooleanField(blank=True, null=True)),
                ('neuro_4', models.BooleanField(blank=True, null=True)),
                ('neuro_5', models.BooleanField(blank=True, null=True)),
                ('neuro_6', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'neurologiques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(blank=True, max_length=255, null=True)),
                ('dte', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'operation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, max_length=255, null=True)),
                ('mlle', models.CharField(blank=True, max_length=255, null=True)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('corps', models.CharField(blank=True, max_length=255, null=True)),
                ('family_stats', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital_service', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pediatriques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pediatri_1', models.BooleanField(blank=True, null=True)),
                ('pediatri_2', models.BooleanField(blank=True, null=True)),
                ('pediatri_3', models.BooleanField(blank=True, null=True)),
                ('pediatri_4', models.BooleanField(blank=True, null=True)),
                ('pediatri_5', models.BooleanField(blank=True, null=True)),
                ('pediatri_6', models.CharField(blank=True, max_length=255, null=True)),
                ('pediatri_7', models.BooleanField(blank=True, null=True)),
                ('pediatri_8', models.IntegerField(blank=True, null=True)),
                ('pediatri_9', models.IntegerField(blank=True, null=True)),
                ('pediatri_10', models.IntegerField(blank=True, null=True)),
                ('pediatri_11', models.IntegerField(blank=True, null=True)),
                ('pediatri_12', models.BooleanField(blank=True, null=True)),
                ('pediatri_13', models.BooleanField(blank=True, null=True)),
                ('pediatri_14', models.BooleanField(blank=True, null=True)),
                ('pediatri_15', models.BooleanField(blank=True, null=True)),
                ('pediatri_16', models.BooleanField(blank=True, null=True)),
                ('pediatri_17', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pediatriques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('discription', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pulmonaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulm_1', models.BooleanField(blank=True, null=True)),
                ('pulm_2', models.BooleanField(blank=True, null=True)),
                ('pulm_3', models.BooleanField(blank=True, null=True)),
                ('pulm_4', models.BooleanField(blank=True, null=True)),
                ('pulm_5', models.BooleanField(blank=True, null=True)),
                ('pulm_6', models.BooleanField(blank=True, null=True)),
                ('pulm_7', models.BooleanField(blank=True, null=True)),
                ('pulm_8', models.BooleanField(blank=True, null=True)),
                ('pulm_9', models.BooleanField(blank=True, null=True)),
                ('pulm_10', models.BooleanField(blank=True, null=True)),
                ('pulm_11', models.BooleanField(blank=True, null=True)),
                ('pulm_12', models.BooleanField(blank=True, null=True)),
                ('pulm_13', models.BooleanField(blank=True, null=True)),
                ('pulm_14', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pulmonaires',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Renaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renau_1', models.BooleanField(blank=True, null=True)),
                ('renau_2', models.BooleanField(blank=True, null=True)),
                ('renau_3', models.BooleanField(blank=True, null=True)),
                ('renau_4', models.BooleanField(blank=True, null=True)),
                ('renau_5', models.BooleanField(blank=True, null=True)),
                ('renau_6', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'renaux',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rhumatologiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rhumatol_1', models.BooleanField(blank=True, null=True)),
                ('rhumatol_2', models.BooleanField(blank=True, null=True)),
                ('rhumatol_3', models.BooleanField(blank=True, null=True)),
                ('rhumatol_4', models.CharField(blank=True, max_length=255, null=True)),
                ('rhumatol_5', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rhumatologiques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'traitement',
                'managed': False,
            },
        ),
    ]
