# Generated by Django 3.2.1 on 2021-06-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_medical_pics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pics',
            name='dossierid',
            field=models.ForeignKey(db_column='dossierid', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.dossier'),
        ),
    ]
